name: Automated test for effectivemobile

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target test
        required: true
        type: choice
        default: first_test
        options:
          - first_test
          - second_test
          - all_tests

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          wget -q https://storage.googleapis.com/chrome-for-testing-public/120.0.6099.109/linux64/chromedriver-linux64.zip
          unzip -q chromedriver-linux64.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver-linux64/chromedriver

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ===== ИСТОРИЯ =====
      - name: Download allure history
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: allure-history
          path: allure-results/history

      # ===== ЗАПУСК ТЕСТОВ =====
      - name: Run first test
        if: ${{ github.event.inputs.deployment_target == 'first_test' }}
        run: pytest tests/test_effectivemobile.py::test_vacancy --alluredir=allure-results -v

      - name: Run second test
        if: ${{ github.event.inputs.deployment_target == 'second_test' }}
        run: pytest tests/test_effectivemobile.py::test_review --alluredir=allure-results -v

      - name: Run all tests
        if: ${{ github.event.inputs.deployment_target == 'all_tests' }}
        run: pytest tests/test_effectivemobile.py --alluredir=allure-results -v

      # ===== СОХРАНЕНИЕ РЕЗУЛЬТАТОВ И ИСТОРИИ =====
      - name: Upload allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 5

      - name: Upload allure history
        uses: actions/upload-artifact@v4
        with:
          name: allure-history
          path: allure-results/history || allure-results
          retention-days: 5


  generate-report:
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Allure
        run: |
          wget -q https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz
          tar -zxvf allure-2.24.1.tgz
          ./allure-2.24.1/bin/allure --version

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate report
        run: |
          rm -rf _site
          ./allure-2.24.1/bin/allure generate allure-results -o _site --clean
          ls -la _site

      - name: Upload report
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: generate-report
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4